appcache/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
     # include the built-in auth urls for the built-in views
  path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/addprofile/', views.ProfileCreate.as_view(), name='profiles_create'),
    path('tech/', views.technologies_index, name='tech_index'),
    path('tech/create', views.TechnologieCreate.as_view(), name='tech_create'),
    path('apps/create', views.AppCreate.as_view(), name='apps_create'),
    path('apps/', views.apps_index, name='apps_index'),
    path('apps/<int:app_id>/assoc_user/', views.assoc_user, name='assoc_user'),
    path('apps/<int:app_id>/', views.apps_detail, name='apps_detail'),
    path('apps/<int:app_id>/addnote', views.apps_addnote, name='apps_addnote'),
    path('accounts/users/', views.users_index, name='users_index'),
    path('accounts/<int:user_id>/', views.users_detail, name='users_detail'),
    path('accounts/profile/', views.profile, name='profile'),
    path('apps/<int:app_id>/disassoc_user/', views.disassoc_user, name='disassoc_user'),
    path('accounts/<int:pk>/update', views.ProfileUpdate.as_view(), name='profiles_update'),
    path('apps/<int:app_id>/addlink', views.apps_addlink, name='apps_addlink'),
    path('apps/<int:app_id>/users', views.attached_users, name='attached_users'),
    path('apps/search/', views.apps_search, name='apps_search'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.TextField(default='https://t4america.org/wp-content/uploads/2016/10/Blank-User.jpg')
    bio = models.TextField(default='Hitting The Code Hard!')
    github = models.CharField(max_length=200, default='')
    linkedin = models.CharField(max_length=200, default='')


class Technologie(models.Model):
    name = models.CharField(max_length=50)
    docs = models.CharField(max_length=250, default='https://google.com/')
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering: ['name']

class App(models.Model):
    creator = models.IntegerField()
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    tech = models.ManyToManyField(Technologie)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('apps_detail', kwargs={'app_id': self.id})

class Note(models.Model):
    date = models.DateField(auto_now_add=True)
    message = models.TextField()
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.first_name} posted {self.message} on {self.date}"

class BuildLink(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    link = models.CharField(max_length=200, default='')

    def __str__(self):
        return f"{self.name} linked by {self.user.id}"

class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

main_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Note, BuildLink, Subscribe

class UserForm(UserCreationForm):
    class Meta(UserCreationForm): 
        model = User
        fields = ['username', 'first_name', 'email']

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['message']

class BuildLinkForm(ModelForm):
    class Meta:
        model = BuildLink
        fields = ['name', 'link']

class SubscribeForm(ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'
    
    

main_app/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Profile, Technologie, App, User, Note, BuildLink
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserForm, NoteForm, BuildLinkForm, SubscribeForm
from django.db.models import Q
from appcache.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


def home(request):
  subscribe_form = SubscribeForm()
  if request.method == 'POST':
    subscribe_form = SubscribeForm(request.POST)
    subject = 'Welcome To The Dev Community at App Cache'
    if request.user.is_authenticated:
      message = f'Hey {request.user.first_name}, thanks for subscribing to the App Cache Flash! We hope you enjoy sharing and comparing with your fellow coders. Create some app ideas here, implement a few ideas there, and be sure to network with each other on Linkedin!'
    else:
      message = f"Hey Friend, thanks for subscribing to the App Cache Flash! If you have already signed on with us, we hope you continue to enjoy sharing and comparing with your fellow coders. Create some app ideas here, implement a few ideas there, and be sure to network with each other on Linkedin! If you haven't decided on making an account yet, THIS is your sign to join the party, as one of my favorite coding instructors would say."
    recipient = str(subscribe_form['email'].value())
    send_mail(subject, message, EMAIL_HOST_USER, [recipient], fail_silently = False)
    return render(request, 'subscribe/success.html', {'recipient': recipient})
  return render(request, 'home.html', {'subscribe_form': subscribe_form})

def about(request):
    return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('profiles_create')
    #   COME BACK AND CHANGE REDIRECT LOCATION
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def users_index(request):
  users = User.objects.exclude(id=request.user.id)
  return render(request, 'accounts/index.html', {'users': users})

@login_required
def users_detail(request, user_id):
  current_user = User.objects.get(id=user_id)
  apps_you_dont_have = App.objects.exclude(users__exact=request.user)
  return render(request, 'accounts/detail.html', {'current_user': current_user, 'apps_you_dont_have': apps_you_dont_have})

@login_required
def profile(request):
  user = User.objects.get(id=request.user.id)
  return render(request, 'accounts/profile.html', {'user': user})


@login_required
def subscribe(request):
  subscribe_form = SubscribeForm()
  if request.method == 'POST':
    subscribe_form = SubscribeForm(request.POST)
    subject = 'Welcome To The Dev Community at App Cache'
    message = 'Thanks for subscribing to the App Cache Flash! We hope you enjoy sharing and comparing with your fellow coders. Create some app ideas here, implement a few ideas there, and be sure to network with each other on Linkedin!'
    recipient = str(subscribe_form['email'].value())
    send_mail(subject, message, EMAIL_HOST_USER, [recipient], fail_silently = False)
    return render(request, 'subscribe/success.html', {'recipient': recipient})
  return render(request, 'home.html', {'subscribe_form': subscribe_form})

@login_required
def apps_index(request):
  apps = App.objects.all()
  apps_you_dont_have = App.objects.exclude(users__exact=request.user)
  tech = Technologie.objects.all()
  return render(request, 'apps/index.html', {'apps_you_dont_have': apps_you_dont_have, 'apps': apps, 'tech': tech})

@login_required
def apps_detail(request, app_id):
  app = App.objects.get(id=app_id)
  user = User.objects.get(id=request.user.id)
  note_form = NoteForm()
  buildlink_form = BuildLinkForm()
  creator = User.objects.get(id=app.creator)
  return render(request, 'apps/detail.html', {
    'app': app, 'user': user, 'note_form': note_form, 'buildlink_form': buildlink_form, 'creator': creator})

@login_required
def apps_addlink(request, app_id):
  form = BuildLinkForm(request.POST)
  if form.is_valid():
    new_buildlink = form.save(commit=False)
    new_buildlink.app_id = app_id
    new_buildlink.user_id = request.user.id
    new_buildlink.save()
  return redirect('apps_detail', app_id=app_id)

@login_required
def assoc_user(request, app_id):
  App.objects.get(id=app_id).users.add(request.user)
  return redirect('apps_detail', app_id=app_id)

@login_required
def attached_users(request, app_id):
  app = App.objects.get(id=app_id)
  apps_you_dont_have = App.objects.exclude(users__exact=request.user)

  return render(request, 'apps/attached_users.html', {'app': app, 'apps_dont_dont_have': apps_you_dont_have})

@login_required
def apps_addnote(request, app_id):
  form = NoteForm(request.POST)
  if form.is_valid():
    new_note = form.save(commit=False)
    new_note.app_id = app_id
    new_note.user_id = request.user.id
    new_note.save()
  return redirect('apps_detail', app_id=app_id)

@login_required
def disassoc_user(request, app_id):
  app = App.objects.get(id=app_id)
  app.users.remove(request.user.id)
  return redirect('profile')

@login_required
def apps_search(request):
  query = request.GET.get('q')
  apps = App.objects.filter(Q(tech__exact=query))
  tech = Technologie.objects.all()

  return render(request, 'apps/search_results.html', {'apps': apps, 'tech': tech} )

@login_required
def technologies_index(request):
  tech = Technologie.objects.all()
  return render(request, 'technologies/index.html', {'tech': tech})

class ProfileCreate(LoginRequiredMixin, CreateView):
  model = Profile
  fields = ['photo', 'bio', 'linkedin', 'github']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  success_url = '/accounts/profile/'

class ProfileUpdate(LoginRequiredMixin, UpdateView):
  model = Profile
  fields = ['photo', 'bio', 'github', 'linkedin']
  success_url='/accounts/profile/'

class TechnologieCreate(LoginRequiredMixin, CreateView):
  model = Technologie
  fields = '__all__'
  success_url = '/tech/'

class AppCreate(LoginRequiredMixin, CreateView):
  model = App
  fields = ['name', 'description', 'tech']

  def form_valid(self, form):
    self.object = form.save(commit=False)
    self.object.creator = self.request.user.id
    self.object = form.save()
    App.objects.get(id=self.object.id).users.add(self.request.user)
    return redirect('/apps/')

main_app/templates/apps/attached_users.html
{% extends 'base.html' %} {% block content %}

<div class="page-top">
  <h1>Fellow Coders of {{app.name}}</h1>
</div>

<div class="card-list">
  {% for attached_user in app.users.all %}
  <div class="card m-5 shadow" style="width: 18rem">
    <img
      src="{{ attached_user.profile.photo }}"
      class="card-img-top shadow"
      alt="user associated headshot"
    />
    <div class="card-body shadow">
      <h5 class="card-title shadow">{{attached_user.first_name}}</h5>
      <p class="card-text shadow">Year Joined: {{attached_user.date_joined.year}}</p>
      <form action="{% url 'users_detail' attached_user.id %}">
        <button type="submit" class="btn btn-sm btn-secondary shadow">Profile</button>
      </form>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

main_app/templates/apps/detail.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="page-top mb-3">
  <div class="card shadow" style="width: auto">
    <div class="card-body shadow">
      <h5 id="app-title" class="card-title shadow">{{app.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted shadow">
        First Added By:
        <a href="{% url 'users_detail' creator.id %}">{{creator.first_name}}</a>
      </h6>
      <p class="card-text shadow">{{app.description}}</p>
      <div class="card-body">
        <div class="card shadow" style="width: auto">
          <label class="card-label shadow">Technology Used</label>
          <ul class="list-group list-group-flush">
            {% for tech in app.tech.all %}
            <li class="list-group-item">
              <a target="_blank" href="{{tech.docs}}">{{ tech.name }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div>
        {% if user.id in app.users %}
        <h1 class="shadow">You've got this in your build list already</h1>
        {% else %}
        <form action="{% url 'assoc_user' app.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-sm btn-secondary shadow">
            Add This App To Your List!
          </button>
        </form>
        {% endif %}
      </div>
    </div>

    <div class="card" style="width: auto">
      <div class="card-body">
        <form action="{% url 'apps_addnote' app.id %}" method="post">
          {% csrf_token %} 
          <div class="shadow profile-form">
          {{note_form|crispy}}
        </div>
          <button type="submit" class="btn btn-sm btn-secondary shadow">Add Note</button>
        </form>
      </div>
    </div>

    <div class="card" style="width: auto">
      <a
        class="btn btn-sm btn-secondary build-list-btn"
        data-bs-toggle="collapse"
        href="#multiCollapseExample2"
        role="button"
        aria-expanded="false"
        aria-controls="multiCollapseExample2"
        >Notes</a
      >
      <div class="row">
        <div class="col">
          <div class="collapse multi-collapse" id="multiCollapseExample2">
            <div class="card card-body">
              {% if app.note_set.count %}
              <table class="table table-striped shadow">
                <thead>
                  <tr>
                    <th>Notes:</th>
                    <th>Date Posted</th>
                    <th>Posted By</th>
                  </tr>
                </thead>
                <tbody>
                  {% for note in app.note_set.all %}
                  <tr>
                    <td>{{note.message}}</td>
                    <td>{{note.date}}</td>
                    <td>
                      <a href="{% url 'users_detail' note.user.id %}"
                        >{{note.user.first_name}}</a
                      >
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <h4>No Notes On This Build Idea Yet</h4>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <h4>Show Off Your Finished Builds Based On This Idea</h4>
          <form action="{% url 'apps_addlink' app.id %}" method="post">
            {% csrf_token %} 
            {{buildlink_form|crispy}}
            <button type="submit" class="btn btn-sm btn-secondary shadow">Add Link</button>
          </form>
        </div>

        <a
          class="btn btn-secondary"
          data-bs-toggle="collapse"
          href="#multiCollapseExample3"
          role="button"
          aria-expanded="false"
          aria-controls="multiCollapseExample3"
          >Finished Builds</a
        >
        <div class="row">
          <div class="col">
            <div class="collapse multi-collapse" id="multiCollapseExample3">
              <div class="card card-body">
                {% if app.buildlink_set.count %}
                <table class="table table-striped shadow">
                  <thead>
                    <tr>
                      <th>Built Apps</th>
                      <th>Posted By</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for link in app.buildlink_set.all %}
                    <tr>
                      <td>
                        <a href="{{link.link}}" target="_blank"
                          >{{link.name}}</a
                        >
                      </td>
                      <td>
                        <a href="{% url 'users_detail' link.user.id %}"
                          >{{link.user.first_name}}</a
                        >
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% else %}
                <h4>No Builds Yet, Give It A Go!</h4>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/apps/index.html
{% extends 'base.html' %}

{% block content %}
<div class="page-top card shadow mb-3">
    <h1>App Ideas</h1>
    <span>Don't see one that speaks to you? Go <a href="{% url 'apps_create' %}">Create An App!</a></span>
    <form action="{% url 'apps_search' %}" method="get">
        <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle shadow" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tech Filter
            </button>
            <ol class="dropdown-menu dropdown-menu-dark scrollable-menu shadow" role="menu" style="height: auto;max-height: 180px; overflow-x: hidden;" aria-labelledby="dropdownMenuButton2">
        {% for tech in tech.all %}
        <li class="dropdown-item">
            {{tech.name}}
            <input type="checkbox" name="q" value="{{tech.id}}">
        </li>
        {% endfor %}
            </ol>
            <button type="submit" class="btn btn-sm btn-secondary shadow">Search Apps</button>
        </div>
    </form>
</div>

{% if apps.count %}
<div class="card-list">
    {% for app in apps %}
    <div class="card shadow rounded">
            <div class="card-header shadow">{{ app.name }}</div>
        <div class="card-body">
            <form action="{% url 'apps_detail' app.id %}">
                <button type="submit" class="btn btn-sm btn-secondary shadow">Details</button>
            </form>
            {% if app in apps_you_dont_have.all %}
        <form action="{% url 'assoc_user' app.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-secondary shadow">
                    Add To List!
                </button>
            </form> 
            {% else %}
            <p>You Have This On Your Build List</p>
            {% endif %}
    </div>
</div>
    {% endfor %}
</div>
{% else %}
<div class="card-body">
    You've collected all current app ideas in the App Cache, go build some!
</div>
{% endif %}

{% endblock %}

main_app/templates/apps/search_results.html
{% extends 'base.html' %}

{% block content %}

<div class="page-top card shadow">
  <h1>Search Results</h1>
<hr>
  <form action="{% url 'apps_search' %}" method="get">
    <div class="btn-group">
        <button class="btn btn-sm btn-secondary btn-sm dropdown-toggle shadow" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Tech Filter
        </button>
        <ol class="dropdown-menu dropdown-menu-dark scrollable-menu shadow" role="menu" style="height: auto;max-height: 180px; overflow-x: hidden;" aria-labelledby="dropdownMenuButton2">
    {% for tech in tech.all %}
    <li class="dropdown-item">
    {{tech.name}}
    <input type="checkbox" name="q" value="{{tech.id}}">
</li>
    {% endfor %}
    </ol>
    <button type="submit" class="btn btn-sm btn-secondary shadow">Search Apps</button>
</form>
</div>
</div>


{% if apps.count %}
<div class="card-list">
    {% for app in apps %}
        <div class="card border-light shadow m-5 rounded">
            <div class="card-header shadow">{{ app.name }}</div>
        <div class="card-body">
        </div>
        <div class="card-body">
        <form action="{% url 'apps_detail' app.id %}">
            <button type="submit" class="btn btn-secondary shadow">Details</button>
        </form>
        {% if app in apps_you_dont_have.all %}
      <form action="{% url 'assoc_user' app.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary shadow">
                Add To List!
            </button>
        </form> 
        {% else %}
        <p class="shadow alert">You Have This On Your Build List</p>
        {% endif %}
    </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="card-body">
    There aren't currently app ideas in circulation that use that tech, <a href="{% url 'apps_create' %}">go make one!</a>
</div>
{% endif %}


{% endblock %}